# Gary A. Stafford (2022-09-19)

FROM openjdk:17-jdk

COPY build/libs/kstreams-kafka-demo-1.0.0-all.jar /tmp/kstreams-kafka-demo-1.0.0-all.jar

#ENTRYPOINT ["tail", "-f", "/dev/null"]

CMD ["java", "-jar", "/tmp/kstreams-kafka-demo-1.0.0-all.jar"]


