# Gary A. Stafford (2022-09-19)

FROM openjdk:17-jdk-alpine3.14

COPY build/libs/kstreams-kafka-demo-1.0.0-all.jar /home/kstreams-kafka-demo-1.0.0-all.jar

CMD ["java","-jar","/home/kstreams-kafka-demo-1.0.0-all.jar"]